package ru.nikolyashka.breakingbadsample.ui.favorites.holder

import ru.nikolyashka.breakingbadsample.databinding.ItemEmptyFavoritesBinding
import ru.nikolyashka.breakingbadsample.ui.characters.adapter.holders.CommonCharacterViewHolder

class FavoritesEmptyViewHolder(binding: ItemEmptyFavoritesBinding) : CommonCharacterViewHolder(binding)